name: Check Redirects

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  check_redirects:
    # do not run on PRs in forks
    if: github.repository == 'mdn/translated-content'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # This is a "required" workflow so path filtering can not be used:
      # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
      # We have to rely on a custom filtering mechanism to run the checks only if required files are modified.
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        name: See if any file needs checking
        id: filter
        with:
          filters: |
            required_files:
              - ".nvmrc"
              - "files/**"
              - ".github/workflows/pr-check_redirects.yml"

      - uses: actions/checkout@v4
        if: steps.filter.outputs.required_files == 'true'
        with:
          repository: mdn/content
          path: mdn/content

      - name: Setup Node.js environment
        if: steps.filter.outputs.required_files == 'true'
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          cache-dependency-path: mdn/content/yarn.lock

      - name: Install all yarn packages
        if: steps.filter.outputs.required_files == 'true'
        working-directory: ${{ github.workspace }}/mdn/content
        run: |
          yarn --frozen-lockfile
        env:
          # https://github.com/microsoft/vscode-ripgrep#github-api-limit-note
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check redirects file(s)
        if: steps.filter.outputs.required_files == 'true'
        env:
          CONTENT_ROOT: ${{ github.workspace }}/mdn/content/files
          CONTENT_TRANSLATED_ROOT: ${{ github.workspace }}/files
        working-directory: ${{ github.workspace }}/mdn/content
        run: |
          yarn content validate-redirects
